
spring:
  application:
    name: library-events-producer
  config:
    activate:
      on-profile: dev

  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer